bgC = (0, 0, 0) #Color of the background, usually black.
size = (1200, 600) #The size of the screen.
FLR = 10 #Maximum radius of a Flatlander.
foodR = 10 #Maximum radius of a food pallet
FLColor = (255, 0, 0) #Color of a Flatlander.
foodColor = (0, 255, 0) #Color of a food pallet
nFL = 50 #The starting number of Flatlanders.
nFood = 30 #Number of food units
speed = "Full" #When this is one, each sim tick lasts 1 second. 2 Means that 2 sim ticks last 1 second. Set to "Full" (including the quotes) to run as fast as possible.
maxSpeed = [4, 4]
maxEnergy = 200
